server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradefirm
    username: postgres
    password: 111111
    driver-class-name: org.postgresql.Driver

graphql:
  packages: "paulpaulych.tradefirm"

