server:
  port: 3000
  error:
    includeStacktrace=ALWAYS:spring: ALWAYS

jwt:
  secret-key: blablablablablablablalbalbalbalbalbalbalbalba

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pgdb
    username: user
    password: changeme
    driver-class-name: org.postgresql.Driver

graphql:
  packages:
    - "paulpaulych.tradefirm"
    - "java.util"

order:
  create:
    fixedRateMillis: 60000
    fetchSize: 5

fakesupplier:
  createDelivery:
    fixedRateMillis: 60000
